//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enumeration
    {
        public int id { get; set; }
        public string enumerationType { get; set; }
        public string value { get; set; }
        public int sortOrder { get; set; }
        public Nullable<int> i18nKey { get; set; }
        public byte isDefault { get; set; }
    
        public virtual Keyword Keyword { get; set; }
    }
}
