//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransMan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        public int id { get; set; }
        public string translation1 { get; set; }
        public Nullable<int> identifier { get; set; }
        public Nullable<int> language { get; set; }
    
        public virtual Keyword Keyword { get; set; }
        public virtual ISOLanguage ISOLanguage { get; set; }
    }
}
